// Generated by scripts/generate-style-palette.mjs — do not edit by hand.
// Re-run: npm run generate:style-palette

export const stylePaletteSwatches = [
  {
    "color": "#5f5437",
    "name": "Forest Moss",
    "src": "/images/portfolio/mcminnville-wedding/04.jpg",
    "alt": "Bride and groom in the forest with a long veil flowing in the wind"
  },
  {
    "color": "#765337",
    "name": "Red Rock Clay",
    "src": "/images/portfolio/sedona-portraits/05.jpg",
    "alt": "Couple holding hands among red rock formations in Sedona"
  },
  {
    "color": "#a04a3f",
    "name": "Neon Terracotta",
    "src": "/images/portfolio/las-vegas-wedding/01.jpg",
    "alt": "Bride and groom exchanging vows in front of the Lady Luck neon sign"
  },
  {
    "color": "#6a4f3e",
    "name": "Brick Warmth",
    "src": "/images/portfolio/franklin-engagement/02.jpg",
    "alt": "Couple embracing in front of the Franklin Theatre"
  },
  {
    "color": "#513f2c",
    "name": "Autumn Rust",
    "src": "/images/portfolio/chattanooga-engagement/04.jpg",
    "alt": "Couple walking through a leaf-covered forest path holding hands"
  },
  {
    "color": "#7d5f3e",
    "name": "Aspen Green",
    "src": "/images/portfolio/flagstaff-engagement/01.jpg",
    "alt": "Couple laughing together on a mattress in a snowy aspen forest"
  }
] as const;

export type StylePaletteSwatch = (typeof stylePaletteSwatches)[number];

export type StylePaletteColor = StylePaletteSwatch["color"];

/** Flat list of generated palette colors. */
export const stylePalette = stylePaletteSwatches.map((swatch) => swatch.color);
